# Generated by Django 5.1 on 2024-08-25 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BlogApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email_confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
